website/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from . import db
from .models import User
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from io import BytesIO
from .sec_modules.email_checking import isEmailValid
from .sec_modules.password_checking import password_complexity
import os, base64, onetimepass, pyqrcode

auth = Blueprint("auth", __name__)

@auth.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == "POST":
        email = request.form.get("email")
        username = request.form.get("username")
        password = request.form.get("password")
        password2 = request.form.get("password2")
        otp_secret = base64.b32encode(os.urandom(15)).decode('utf-8')

        email_exists = User.query.filter_by(email=email).first()
        username_exists = User.query.filter_by(username=username).first()
        if email_exists:
            flash('Error occurs! Error Code: 1', category='error')
            print('Error - 1 - Email has already been registered!')
        elif username_exists:
            flash('Error occurs! Error Code: 2', category='error')
            print('Error - 2 - The username has been taken')
        elif password != password2:
            flash("Password doesn't match!", category='error')
            print("Error - User passwords do not match")
        elif not password_complexity(password):
            flash("Password complexity fails!", category='error')
            print("Error - Password complexity fails")
        elif not isEmailValid(email):
            flash("Invalid email!", category='error')
            print("Error - Invalid email provided")
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(password, method='sha256'), otp_secret=otp_secret)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("User created!")
            return redirect(url_for("auth.two_factor_setup", username=username))
    return render_template("register.html", user=current_user)

@auth.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        otp = request.form.get('otp')
        user = User.query.filter_by(email=email).first()
        if user:
            if (    check_password_hash(user.password, password)
                and onetimepass.valid_totp(otp, user.otp_secret)
               ):
                flash("Login successful!", category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash("Login Error!", category='error')
        else:
            flash("Login Error!", category='error')
    return render_template("login.html", user=current_user)

@auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You have successfully logged out!", category="success")
    return redirect(url_for("views.home"))

@auth.route("/two_factor_setup")
@login_required
def two_factor_setup():
    username = request.args.get('username')
    user = User.query.filter_by(username=username).first()
    otp_secret = user.otp_secret
    logout_user()
    totp_uri = f'otpauth://totp/DamnDumpSite:{username}?secret={otp_secret}&issuer=DamnDumpSite'
    qrcode = pyqrcode.create(totp_uri)
    stream = BytesIO()
    qrcode.svg(stream, scale=5)
    qr = stream.getvalue().decode('utf-8')
    return render_template('two-factor-setup.html', user=current_user, qr=qr, otp_secret=otp_secret), 200, {
            'Cache-Control': 'no-cache, no-store, must-revalidate',
            'Pragma': 'no-cache',
            'Expires': '0'
        }

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/0493ddefd6.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dom-to-image/2.6.0/dom-to-image.js"></script>
    <title>Damn Dump Site - {% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-dark navbar-expand-lg bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <a class="nav-item nav-link" href="/">Home</a>
                {% if user.is_authenticated %}   
                    <a class="nav-item nav-link" href="/create-post">Create Post</a>
                    <a class="nav-item nav-link" href="/base64">Base64 En|Decoder</a>
                    <a class="nav-item nav-link" href="/timeline">Timeline</a>
                    <a class="nav-item nav-link" href="/logout">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="/login">Login</a>
                    <a class="nav-item nav-link" href="/register">Register</a>
                {% endif %}
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == "error" %}
                <div class="alert alert-danger alter-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
                {% else %}
                <div class="alert alert-success alter-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
                </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <div class="container">
        {% block footer %}{% endblock %}
    </div>
    <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
</body>
</html>

website/templates/base64.html
{% extends "base.html" %}

{% block title %}
Base64 Encoder / Decoder
{% endblock %}

{% block content %}
<h1 align="center">Base64 En|Decode</h1>
<form method="post">
    <textarea name="text" id="text" class="form-control" rows="10"></textarea>
    <br/>
    <div align="center">
        <button type="submit" class="btn btn-lg btn-primary" name="submit_button" value="encode">Encode</button>
        <button type="submit" class="btn btn-lg btn-primary" name="submit_button" value="decode">Decode</button>
        <a href="/home"><button type="button" class="btn btn-lg btn-secondary">Back</button></a>
    </div>
</form>

<br/>

<h3 align="center">Result</h3>
<textarea name="result" id="result" class="form-control" rows="10">{{result}}</textarea>

{% endblock %}

website/templates/create_post.html
{% extends "base.html" %}

{% block title %}
Create Post
{% endblock %}

{% block content %}
<h1 align="center">Write a Post</center></h1>
<form method="post">
    <textarea name="text" id="text" class="form-control" rows="20"></textarea>
    <br/>
    <div align="center">
        <button type="submit" class="btn btn-lg btn-primary">Post</button>
        <span class="tab"> </span>
        <a href="/home"><button type="button" class="btn btn-lg btn-secondary">Back</button></a>
    </div>
</form>
<br/>
{% endblock %}

website/templates/home.html
{% extends "post_div.html" %}

{% block title %}
Home
{% endblock %}

{% block header %}
Post
{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}

{% block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="text" id="email" name="email" class="form-control" placeholder="Input your email"></label>
        <label for="password">Password</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Input your password"></label>
        <label for="token">OTP</label>
        <input type="password" id="otp" name="otp" class="form-control" placeholder="Input your OTP"></label>
        <br/>
        <div align="center">
            <button class="btn btn-primary" type="submit">Login</button>
        </div>        
    </div>
</form>
{% endblock %}

website/templates/post_div.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}
    <h1 align="center">{% block header %}Posts{% endblock %}</h1>
    <div id="posts">
        {% for post in posts %}
        <div class="card border-dark">
            <div class="card-header d-flex justify-content-between align-items-center">
                <a href="/posts/{{post.user.username}}">{{post.user.username}}</a>     
                <div>
                    {{ post.likes|length }}
                    <a href="/like-post/{{post.id}}"><i class="fa-regular fa-thumbs-up"></i></a>
                    {% if post.author == user.id %}
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-bs-toggle="dropdown"></button>
                        <ul class="dropdown-menu"><li><a href="/delete-post/{{post.id}}" class="dropdown-item">Delete</a></li></ul>
                    </div>
                    {% endif %}
                </div>
            </div>
            <div class="card-body">
                <div class="card-text">{{post.text}}</div>
                <br/>
                <div class="collapse" id="comments-{{post.id}}">
                    <div class="card">
                        <div class="card-body" id="comments-expanded-{{post.id}}">
                            {% for comment in post.comments %}
                                <div class="d-flex justify-content-between align-items-center">
                                    <div><a href="/posts/{{comment.user.username}}">{{comment.user.username}}</a>: {{comment.text}}</div>
                                    <div>
                                        <small class="text-muted">{{comment.date_created}}</small>
                                        {% if comment.author == current_user.id or post.author == current_user.id %}
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-bs-toggle="dropdown"></button>
                                            <ul class="dropdown-menu"><li><a href="/delete-comment/{{comment.id}}" class="dropdown-item">Delete</a></li></ul>
                                        </div>
                                        {% endif %}
                                    </div>
                                </div>    
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <p class="card-text">
                    {% if post.comments|length > 0 %}
                        <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
                            <small>View {{post.comments|length}} comments</small>
                        </a>
                    {% else %}
                        <small class="text-muted">No comment</small>
                    {% endif %}
                </p>
                <br/>
                <form class="input-group mb-3" method="post" action="/create-comment/{{post.id}}">
                    <input type="text" id="text" name="text" class="form-control" placeholder="Your Comment" />
                    <button type="submit" class="btn btn-primary">Comment</button>
                </form>
            </div>
            <div class="card-footer text-muted">
                <small class="card-text">{{post.date_created}}</small>
            </div>
        </div>
        <br/>
        {% endfor %}
{% endblock %}

{% block footer %}
<div align="center">
    <a href="/create-post"><button type="button" class="btn btn-primary btn-lg">Create a Post</button></a>
</div>
{% endblock %}

website/templates/posts.html
{% extends "post_div.html" %}

{% block title %}
    {{username}}'s Post
{% endblock %}

{% block header %}
    {{username}}'s Post
{% endblock %}

{% block footer %}
<div align="center">
    <a href="/home"><button type="button" class="btn btn-lg btn-secondary">Back</button>
</div>
{% endblock %}

website/templates/register.html
{% extends "base.html" %}

{% block title %}
Register
{% endblock %}

{% block content %}
<form method="POST">
    <h3 align="center">Register</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="text" id="email" name="email" class="form-control" placeholder="Input your email"></label>
        <label for="usernmae">Username</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="Input your username"></label>
        <label for="password">Password</label>
        <div class="row">
            <div class="card w-75">
                <div class="card">
                    <div class="card-body">
                        <p class="card-text">
                            <input type="password" id="password" name="password" class="form-control" placeholder="Input your password"></label>
                        </p>
                    </div>
                </div>
            </div>
            <div class="card w-25">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Password Complexity requirements</h5>
                        <p class="card-text">
                            1. Length: At least 8 characters<br/>
                            2. Uppercase: At least 1<br/>
                            3. Lowercase: At least 1<br/>
                            4. Special character: At least 1<br/>
                            5. Digit: At least 1
                        </p>
                    </div>
                </div>
            </div>
        </div>
        
        <label for="password2">Confirm your Password</label>
        <input type="password" id="password2" name="password2" class="form-control" placeholder="Input your password again"></label>
        <br/>
        <div align="center">
            <button class="btn btn-primary" type="submit">Register</button>
        </div>        
    </div>
</form>
{% endblock %}

website/templates/timeline.html
{% extends "base.html" %}

{% block title %}
Timeline
{% endblock %}

{% block content %}

<h1 align="center">Timeline Generator</h1>
<div class="card border-dark">
    <div class="card-body">
        <div class="card-text">
            <p>For each line, input in the following format:<br/>
                <p class="user-select-all"><code>[YYYY-mm-dd] | [hh:mm:ss] | [Host] | [Actor] | [Victim] | [Title] | [Description]</code></p>
            </p>
        </div>
        <form method="post">
            <textarea name="text" id="text" class="form-control" rows="20" placeholder="Your timeline data">{{ input_text }}</textarea>
            <br/>
            <div align="center">
                <div class="form-floating">
                    <select id="timezone" name="timezone" class="form-select" aria-label="timezoneselect">
                        <option value="-12:00">(GMT -12:00) Eniwetok, Kwajalein</option>
                        <option value="-11:00">(GMT -11:00) Midway Island, Samoa</option>
                        <option value="-10:00">(GMT -10:00) Hawaii</option>
                        <option value="-09:50">(GMT -9:30) Taiohae</option>
                        <option value="-09:00">(GMT -9:00) Alaska</option>
                        <option value="-08:00">(GMT -8:00) Pacific Time (US &amp; Canada)</option>
                        <option value="-07:00">(GMT -7:00) Mountain Time (US &amp; Canada)</option>
                        <option value="-06:00">(GMT -6:00) Central Time (US &amp; Canada), Mexico City</option>
                        <option value="-05:00">(GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima</option>
                        <option value="-04:50">(GMT -4:30) Caracas</option>
                        <option value="-04:00">(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz</option>
                        <option value="-03:50">(GMT -3:30) Newfoundland</option>
                        <option value="-03:00">(GMT -3:00) Brazil, Buenos Aires, Georgetown</option>
                        <option value="-02:00">(GMT -2:00) Mid-Atlantic</option>
                        <option value="-01:00">(GMT -1:00) Azores, Cape Verde Islands</option>
                        <option value="+00:00" selected="selected">(GMT) Western Europe Time, London, Lisbon, Casablanca</option>
                        <option value="+01:00">(GMT +1:00) Brussels, Copenhagen, Madrid, Paris</option>
                        <option value="+02:00">(GMT +2:00) Kaliningrad, South Africa</option>
                        <option value="+03:00">(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg</option>
                        <option value="+03:50">(GMT +3:30) Tehran</option>
                        <option value="+04:00">(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi</option>
                        <option value="+04:50">(GMT +4:30) Kabul</option>
                        <option value="+05:00">(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent</option>
                        <option value="+05:50">(GMT +5:30) Bombay, Calcutta, Madras, New Delhi</option>
                        <option value="+05:75">(GMT +5:45) Kathmandu, Pokhara</option>
                        <option value="+06:00">(GMT +6:00) Almaty, Dhaka, Colombo</option>
                        <option value="+06:50">(GMT +6:30) Yangon, Mandalay</option>
                        <option value="+07:00">(GMT +7:00) Bangkok, Hanoi, Jakarta</option>
                        <option value="+08:00">(GMT +8:00) Beijing, Perth, Singapore, Hong Kong</option>
                        <option value="+08:75">(GMT +8:45) Eucla</option>
                        <option value="+09:00">(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk</option>
                        <option value="+09:50">(GMT +9:30) Adelaide, Darwin</option>
                        <option value="+10:00">(GMT +10:00) Eastern Australia, Guam, Vladivostok</option>
                        <option value="+10:50">(GMT +10:30) Lord Howe Island</option>
                        <option value="+11:00">(GMT +11:00) Magadan, Solomon Islands, New Caledonia</option>
                        <option value="+11:50">(GMT +11:30) Norfolk Island</option>
                        <option value="+12:00">(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka</option>
                        <option value="+12:75">(GMT +12:45) Chatham Islands</option>
                        <option value="+13:00">(GMT +13:00) Apia, Nukualofa</option>
                        <option value="+14:00">(GMT +14:00) Line Islands, Tokelau</option>
                    </select>
                    <label for="timezone">Timezone</label>
                </div>
                <br/>
                <button type="submit" class="btn btn-lg btn-primary">Generate</button>
                <a id="btn-Convert-Html2Image" class="btn btn-lg btn-primary" onclick="downloadtimeline()">Download</a>
            </div>
        </form>
    </div>
</div>
<br/>


<br/>
<div id="timeline-div">
    <div id="timeline-content" class="page">
        <h2 align="center">Timeline</h2>
        <div id="timeline" class="timeline">
            {% for group in timeline_items %}
                {% for date, event_list in group.items() %}
                <div class="timeline__group">
                    <span class="timeline__date time" aria-hidden="true">{{date}}</span>
                    {% for event in event_list %}
                    <div class="timeline__cards">
                        <div class="timeline__card card">
                            <header class="card__header">
                                <time class="time">
                                    <span class="time__day">{{event.time}}</span>
                                    <span class="time__month">{{event.timezone}}</span>
                                </time>
                                <h3 class="card__title r-title">{{event.title}}</h3>
                            </header>
                            <div class="card__content">
                                <p class="fw-light">Host: {{event.host}} | Actor: {{event.actor}} | Victim: {{event.victim}}</p>
                                <p>{{event.desc}}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endfor %}
            {% endfor %}
        </div>
    </div>
</div>




<script>
    function downloadtimeline() {
        var node = document.getElementById('timeline-div');
        var options = {
            quality: 1,
            bgcolor: "#fff"
        };
        domtoimage.toJpeg(node, options).then(function (dataUrl) {
            var link = document.createElement('a');
            link.download = 'timeline.png';
            link.href = dataUrl;
            link.click();
        });
    };
</script>

  <style>
    .r-title{
    margin-top: var(--rTitleMarginTop, 0) !important;
    margin-bottom: var(--rTitleMarginBottom, 0) !important;
    }
    p:not([class]){
    line-height: var(--cssTypographyLineHeight, 1.78);
    margin-top: var(--cssTypographyBasicMargin, 1em);
    margin-bottom: 0;
    }

    p:not([class]):first-child{
    margin-top: 0;
    }

    /*
    text component
    */

    .text{
    display: var(--textDisplay, inline-flex);
    font-size: var(--textFontSize, 1rem);  
    }

    /*
    time component
    */

    /*
    core styles
    */

    .time{
    display: var(--timeDisplay, inline-flex);
    }

    /*
    extensions
    */

    .time__month{
        margin-left: var(--timelineMounthMarginLeft, .25em);
    }

    .time__hhmmssz{
        margin-left: var(--timelineMounthMarginLeft, .25em);
    }

    /*
    skin
    */

    .time{
    padding: var(--timePadding, .25rem 1.25rem .25rem);
    background-color: var(--timeBackgroundColor, #f0f0f0);

    font-size: var(--timeFontSize, .75rem);
    font-weight: var(--timeFontWeight, 700);
    text-transform: var(--timeTextTransform, uppercase);
    color: var(--timeColor, currentColor);
    }

    /*
    card component
    */

    /*
    core styles
    */

    .card{
    padding: var(--timelineCardPadding, 1.5rem 1.5rem 1.25rem);
    }

    .card__content{
    margin-top: var(--cardContentMarginTop, .5rem);
    }

    /*
    skin
    */

    .card{
    border-radius: var(--timelineCardBorderRadius, 2px);
    border-left: var(--timelineCardBorderLeftWidth, 3px) solid var(--timelineCardBorderLeftColor, var(--uiTimelineMainColor));
    box-shadow: var(--timelineCardBoxShadow, 0 1px 3px 0 rgba(0, 0, 0, .12), 0 1px 2px 0 rgba(0, 0, 0, .24));
    background-color: var(--timelineCardBackgroundColor, #fff);
    }

    /*
    extensions
    */

    .card__title{
    --rTitleMarginTop: var(--cardTitleMarginTop, 1rem);
    font-size: var(--cardTitleFontSize, 1.25rem);
    }

    /*
    =====
    CORE STYLES
    =====
    */

    .timeline{
    display: var(--timelineDisplay, grid);
    grid-row-gap: var(--timelineGroupsGap, 2rem);
    }

    /*
    1. If timeline__year isn't displaed the gap between it and timeline__cards isn't displayed too
    */

    .timeline__date{
    margin-bottom: 1.25rem; /* 1 */
    }

    .timeline__cards{
    display: var(--timeloneCardsDisplay, grid);
    grid-row-gap: var(--timeloneCardsGap, 1.5rem);
    }


    /*
    =====
    SKIN
    =====
    */

    .timeline{
    --uiTimelineMainColor: var(--timelineMainColor, #222);
    --uiTimelineSecondaryColor: var(--timelineSecondaryColor, #fff);

    border-left: var(--timelineLineWidth, 3px) solid var(--timelineLineBackgroundColor, var(--uiTimelineMainColor));
    padding-top: 1rem;
    padding-bottom: 1.5rem;
    }

    .timeline__date{
    --timePadding: var(--timelineYearPadding, .5rem 1.5rem);
    --timeColor: var(--uiTimelineSecondaryColor);
    --timeBackgroundColor: var(--uiTimelineMainColor);
    --timeFontWeight: var(--timelineYearFontWeight, 400);
    }

    .timeline__card{
    position: relative;
    margin-left: var(--timelineCardLineGap, 1rem);
    }

    /*
    1. Stoping cut box shadow
    */

    .timeline__cards{
    overflow: hidden;
    padding-top: .25rem; /* 1 */
    padding-bottom: .25rem; /* 1 */
    }

    .timeline__card::before{
    content: "";
    width: 100%;
    height: var(--timelineCardLineWidth, 2px);
    background-color: var(--timelineCardLineBackgroundColor, var(--uiTimelineMainColor));

    position: absolute;
    top: var(--timelineCardLineTop, 1rem);
    left: -50%;
    z-index: -1;
    }

    /*
    =====
    SETTINGS
    =====
    */
    /**/
    .timeline{
    --timelineMainColor: #4557bb;
    }

    /*
    =====
    DEMO
    =====
    */

    body{
    font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Open Sans, Ubuntu, Fira Sans, Helvetica Neue, sans-serif;
    color: #222;

    background-color: #f0f0f0;
    margin: 0;
    display: flex;
    flex-direction: column;
    }

    p{
    margin-top: 0;
    margin-bottom: 1rem;
    line-height: 1.5;
    }

    p:last-child{
    margin-bottom: 0;
    }

    .page{
    max-width: 47rem;
    padding: 5rem 2rem 3rem;
    margin-left: auto;
    margin-right: auto;
    }


    .substack{
    border:1px solid #EEE; 
    background-color: #fff;
    width: 100%;
    max-width: 480px;
    height: 280px;
    margin: 1rem auto;;
    }


    .linktr{
    display: flex;
    justify-content: flex-end;
    padding: 2rem;
    text-align: center;
    }

    .linktr__goal{
    background-color: rgb(209, 246, 255);
    color: rgb(8, 49, 112);
    box-shadow: rgb(8 49 112 / 24%) 0px 2px 8px 0px;
    border-radius: 2rem;
    padding: .75rem 1.5rem;
    }

    .r-link{
        --uirLinkDisplay: var(--rLinkDisplay, inline-flex);
        --uirLinkTextColor: var(--rLinkTextColor);
        --uirLinkTextDecoration: var(--rLinkTextDecoration, none);

        display: var(--uirLinkDisplay) !important;
        color: var(--uirLinkTextColor) !important;
        text-decoration: var(--uirLinkTextDecoration) !important;
    }
</style>
{% endblock %}

website/templates/two-factor-setup.html
{% extends "base.html" %}

{% block content %}
    <h1>Two Factor Authentication Setup</h1>
    <p>You are almost done! Please start Google Authenticator and scan the following QR Code with it:</p>
    <p>{{ qr | safe }}</p>

    <p>If you cannot see the QR Code, please use the follow button to reveal the OTP secret token.</p>
    <a class="btn btn-primary" data-bs-toggle="collapse" href="#OTPSecret" role="button" aria-expanded="false" aria-controls="OTPSecret">Reval OTP Secret Token</a>
    <div class="collapse" id="OTPSecret">
        <div class="card card-body" style="width: 300px;">
            <code>{{otp_secret}}</code>
        </div>
    </div>

    <p><br/>I'm done, take me to the <a href="{{ url_for('auth.login') }}">Login</a> page!</p>
{% endblock %}